name: CI
on:
  push:
    branches:
      - dev
      - "feat/**"
#1. 테스트
#2. PR
#3. 빌드

env:
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build the project
        run: npm run build

  create-pr:
    needs: run-test
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: create PR test"
          body: "This is a test PR"
          base: main
          branch: ${{ github.ref }}
          token: ${{ secrets.ACCESS_TOKEN_FOR_CI}}
