name: PR Build and Test # 워크플로우의 이름
on: push
# 언제 실행할지에 대한 조건

jobs: # 워크플로우의 작업 목록
  build-and-test:
    strategy:
      matrix:
        node-version: [12, 18]
        os-type: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os-type }}
    steps: # 작업의 단계
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Run tests
        run: npm run test
