#main 브랜치에 push를 하면
#테스트 => 빌드

name: Run Test And Build
#push 이벤트에 대해서만 트리거 됌
on:
  # Trigger Event
  push:
    # Event Filtering
    branches:
      - dev

  workflow_dispatch:
    branches:
      - dev

jobs:
  #1.테스트
  test:
    runs-on: ubuntu-latest
    steps:
      #코드를 가져옴
      - name: Get Codes
        uses: actions/checkout@v4
      #의존성 파일들 설치
      - name: Install Dependencies
        run: npm install
        #테스트 실행
      - name: Run Tests
        run: npm run test

    #2.빌드
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Codes
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build
